name: Avalda Rakvere Eragümnaasiumi veebirakendus

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Lae projekt
        uses: actions/checkout@v6

      - name: Seadista GitHub Pages
        uses: actions/configure-pages@v5

      - name: Paki veebileht
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

      - name: Avalda GitHub Pagesis
        id: deployment
        uses: actions/deploy-pages@v4
